/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProsProIdRouteImport } from './routes/pros.$proId'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppProSubscriptionRouteImport } from './routes/app.pro.subscription'
import { Route as AppProResponsesRouteImport } from './routes/app.pro.responses'
import { Route as AppProOnboardingRouteImport } from './routes/app.pro.onboarding'
import { Route as AppProMatchingRouteImport } from './routes/app.pro.matching'
import { Route as AppProDashboardRouteImport } from './routes/app.pro.dashboard'
import { Route as AppProBillingRouteImport } from './routes/app.pro.billing'
import { Route as AppClientDashboardRouteImport } from './routes/app/client/dashboard'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminSupportRouteImport } from './routes/app.admin.support'
import { Route as AppAdminRequestsRouteImport } from './routes/app.admin.requests'
import { Route as AppAdminPaymentsRouteImport } from './routes/app.admin.payments'
import { Route as AppAdminDashboardRouteImport } from './routes/app.admin.dashboard'
import { Route as AppAdminCategoriesRouteImport } from './routes/app.admin.categories'
import { Route as AppAdminApplicationsRouteImport } from './routes/app.admin.applications'
import { Route as AppClientRequestsIndexRouteImport } from './routes/app/client/requests.index'
import { Route as AppProMatchingIdRouteImport } from './routes/app.pro.matching.$id'
import { Route as AppClientRequestsNewRouteImport } from './routes/app/client/requests.new'
import { Route as AppClientRequestsIdRouteImport } from './routes/app/client/requests.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsProIdRoute = ProsProIdRouteImport.update({
  id: '/pros/$proId',
  path: '/pros/$proId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProSubscriptionRoute = AppProSubscriptionRouteImport.update({
  id: '/pro/subscription',
  path: '/pro/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppProResponsesRoute = AppProResponsesRouteImport.update({
  id: '/pro/responses',
  path: '/pro/responses',
  getParentRoute: () => AppRoute,
} as any)
const AppProOnboardingRoute = AppProOnboardingRouteImport.update({
  id: '/pro/onboarding',
  path: '/pro/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppProMatchingRoute = AppProMatchingRouteImport.update({
  id: '/pro/matching',
  path: '/pro/matching',
  getParentRoute: () => AppRoute,
} as any)
const AppProDashboardRoute = AppProDashboardRouteImport.update({
  id: '/pro/dashboard',
  path: '/pro/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProBillingRoute = AppProBillingRouteImport.update({
  id: '/pro/billing',
  path: '/pro/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppClientDashboardRoute = AppClientDashboardRouteImport.update({
  id: '/client/dashboard',
  path: '/client/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSupportRoute = AppAdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRequestsRoute = AppAdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPaymentsRoute = AppAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCategoriesRoute = AppAdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminApplicationsRoute = AppAdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppClientRequestsIndexRoute = AppClientRequestsIndexRouteImport.update({
  id: '/client/requests/',
  path: '/client/requests/',
  getParentRoute: () => AppRoute,
} as any)
const AppProMatchingIdRoute = AppProMatchingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProMatchingRoute,
} as any)
const AppClientRequestsNewRoute = AppClientRequestsNewRouteImport.update({
  id: '/client/requests/new',
  path: '/client/requests/new',
  getParentRoute: () => AppRoute,
} as any)
const AppClientRequestsIdRoute = AppClientRequestsIdRouteImport.update({
  id: '/client/requests/$id',
  path: '/client/requests/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/search': typeof SearchRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/support': typeof AppSupportRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/pros/$proId': typeof ProsProIdRoute
  '/app/admin/applications': typeof AppAdminApplicationsRoute
  '/app/admin/categories': typeof AppAdminCategoriesRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/payments': typeof AppAdminPaymentsRoute
  '/app/admin/requests': typeof AppAdminRequestsRoute
  '/app/admin/support': typeof AppAdminSupportRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/client/dashboard': typeof AppClientDashboardRoute
  '/app/pro/billing': typeof AppProBillingRoute
  '/app/pro/dashboard': typeof AppProDashboardRoute
  '/app/pro/matching': typeof AppProMatchingRouteWithChildren
  '/app/pro/onboarding': typeof AppProOnboardingRoute
  '/app/pro/responses': typeof AppProResponsesRoute
  '/app/pro/subscription': typeof AppProSubscriptionRoute
  '/app/client/requests/$id': typeof AppClientRequestsIdRoute
  '/app/client/requests/new': typeof AppClientRequestsNewRoute
  '/app/pro/matching/$id': typeof AppProMatchingIdRoute
  '/app/client/requests/': typeof AppClientRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/search': typeof SearchRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/support': typeof AppSupportRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/pros/$proId': typeof ProsProIdRoute
  '/app/admin/applications': typeof AppAdminApplicationsRoute
  '/app/admin/categories': typeof AppAdminCategoriesRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/payments': typeof AppAdminPaymentsRoute
  '/app/admin/requests': typeof AppAdminRequestsRoute
  '/app/admin/support': typeof AppAdminSupportRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/client/dashboard': typeof AppClientDashboardRoute
  '/app/pro/billing': typeof AppProBillingRoute
  '/app/pro/dashboard': typeof AppProDashboardRoute
  '/app/pro/matching': typeof AppProMatchingRouteWithChildren
  '/app/pro/onboarding': typeof AppProOnboardingRoute
  '/app/pro/responses': typeof AppProResponsesRoute
  '/app/pro/subscription': typeof AppProSubscriptionRoute
  '/app/client/requests/$id': typeof AppClientRequestsIdRoute
  '/app/client/requests/new': typeof AppClientRequestsNewRoute
  '/app/pro/matching/$id': typeof AppProMatchingIdRoute
  '/app/client/requests': typeof AppClientRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/search': typeof SearchRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/support': typeof AppSupportRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/pros/$proId': typeof ProsProIdRoute
  '/app/admin/applications': typeof AppAdminApplicationsRoute
  '/app/admin/categories': typeof AppAdminCategoriesRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/payments': typeof AppAdminPaymentsRoute
  '/app/admin/requests': typeof AppAdminRequestsRoute
  '/app/admin/support': typeof AppAdminSupportRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/client/dashboard': typeof AppClientDashboardRoute
  '/app/pro/billing': typeof AppProBillingRoute
  '/app/pro/dashboard': typeof AppProDashboardRoute
  '/app/pro/matching': typeof AppProMatchingRouteWithChildren
  '/app/pro/onboarding': typeof AppProOnboardingRoute
  '/app/pro/responses': typeof AppProResponsesRoute
  '/app/pro/subscription': typeof AppProSubscriptionRoute
  '/app/client/requests/$id': typeof AppClientRequestsIdRoute
  '/app/client/requests/new': typeof AppClientRequestsNewRoute
  '/app/pro/matching/$id': typeof AppProMatchingIdRoute
  '/app/client/requests/': typeof AppClientRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/search'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/profile'
    | '/app/support'
    | '/auth/login'
    | '/auth/register'
    | '/pros/$proId'
    | '/app/admin/applications'
    | '/app/admin/categories'
    | '/app/admin/dashboard'
    | '/app/admin/payments'
    | '/app/admin/requests'
    | '/app/admin/support'
    | '/app/admin/users'
    | '/app/client/dashboard'
    | '/app/pro/billing'
    | '/app/pro/dashboard'
    | '/app/pro/matching'
    | '/app/pro/onboarding'
    | '/app/pro/responses'
    | '/app/pro/subscription'
    | '/app/client/requests/$id'
    | '/app/client/requests/new'
    | '/app/pro/matching/$id'
    | '/app/client/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/search'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/profile'
    | '/app/support'
    | '/auth/login'
    | '/auth/register'
    | '/pros/$proId'
    | '/app/admin/applications'
    | '/app/admin/categories'
    | '/app/admin/dashboard'
    | '/app/admin/payments'
    | '/app/admin/requests'
    | '/app/admin/support'
    | '/app/admin/users'
    | '/app/client/dashboard'
    | '/app/pro/billing'
    | '/app/pro/dashboard'
    | '/app/pro/matching'
    | '/app/pro/onboarding'
    | '/app/pro/responses'
    | '/app/pro/subscription'
    | '/app/client/requests/$id'
    | '/app/client/requests/new'
    | '/app/pro/matching/$id'
    | '/app/client/requests'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/search'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/profile'
    | '/app/support'
    | '/auth/login'
    | '/auth/register'
    | '/pros/$proId'
    | '/app/admin/applications'
    | '/app/admin/categories'
    | '/app/admin/dashboard'
    | '/app/admin/payments'
    | '/app/admin/requests'
    | '/app/admin/support'
    | '/app/admin/users'
    | '/app/client/dashboard'
    | '/app/pro/billing'
    | '/app/pro/dashboard'
    | '/app/pro/matching'
    | '/app/pro/onboarding'
    | '/app/pro/responses'
    | '/app/pro/subscription'
    | '/app/client/requests/$id'
    | '/app/client/requests/new'
    | '/app/pro/matching/$id'
    | '/app/client/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SearchRoute: typeof SearchRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ProsProIdRoute: typeof ProsProIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pros/$proId': {
      id: '/pros/$proId'
      path: '/pros/$proId'
      fullPath: '/pros/$proId'
      preLoaderRoute: typeof ProsProIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pro/subscription': {
      id: '/app/pro/subscription'
      path: '/pro/subscription'
      fullPath: '/app/pro/subscription'
      preLoaderRoute: typeof AppProSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pro/responses': {
      id: '/app/pro/responses'
      path: '/pro/responses'
      fullPath: '/app/pro/responses'
      preLoaderRoute: typeof AppProResponsesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pro/onboarding': {
      id: '/app/pro/onboarding'
      path: '/pro/onboarding'
      fullPath: '/app/pro/onboarding'
      preLoaderRoute: typeof AppProOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pro/matching': {
      id: '/app/pro/matching'
      path: '/pro/matching'
      fullPath: '/app/pro/matching'
      preLoaderRoute: typeof AppProMatchingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pro/dashboard': {
      id: '/app/pro/dashboard'
      path: '/pro/dashboard'
      fullPath: '/app/pro/dashboard'
      preLoaderRoute: typeof AppProDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pro/billing': {
      id: '/app/pro/billing'
      path: '/pro/billing'
      fullPath: '/app/pro/billing'
      preLoaderRoute: typeof AppProBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/client/dashboard': {
      id: '/app/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/app/client/dashboard'
      preLoaderRoute: typeof AppClientDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/support': {
      id: '/app/admin/support'
      path: '/admin/support'
      fullPath: '/app/admin/support'
      preLoaderRoute: typeof AppAdminSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/requests': {
      id: '/app/admin/requests'
      path: '/admin/requests'
      fullPath: '/app/admin/requests'
      preLoaderRoute: typeof AppAdminRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/payments': {
      id: '/app/admin/payments'
      path: '/admin/payments'
      fullPath: '/app/admin/payments'
      preLoaderRoute: typeof AppAdminPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/dashboard': {
      id: '/app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/app/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/categories': {
      id: '/app/admin/categories'
      path: '/admin/categories'
      fullPath: '/app/admin/categories'
      preLoaderRoute: typeof AppAdminCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/applications': {
      id: '/app/admin/applications'
      path: '/admin/applications'
      fullPath: '/app/admin/applications'
      preLoaderRoute: typeof AppAdminApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/client/requests/': {
      id: '/app/client/requests/'
      path: '/client/requests'
      fullPath: '/app/client/requests/'
      preLoaderRoute: typeof AppClientRequestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pro/matching/$id': {
      id: '/app/pro/matching/$id'
      path: '/$id'
      fullPath: '/app/pro/matching/$id'
      preLoaderRoute: typeof AppProMatchingIdRouteImport
      parentRoute: typeof AppProMatchingRoute
    }
    '/app/client/requests/new': {
      id: '/app/client/requests/new'
      path: '/client/requests/new'
      fullPath: '/app/client/requests/new'
      preLoaderRoute: typeof AppClientRequestsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/client/requests/$id': {
      id: '/app/client/requests/$id'
      path: '/client/requests/$id'
      fullPath: '/app/client/requests/$id'
      preLoaderRoute: typeof AppClientRequestsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppProMatchingRouteChildren {
  AppProMatchingIdRoute: typeof AppProMatchingIdRoute
}

const AppProMatchingRouteChildren: AppProMatchingRouteChildren = {
  AppProMatchingIdRoute: AppProMatchingIdRoute,
}

const AppProMatchingRouteWithChildren = AppProMatchingRoute._addFileChildren(
  AppProMatchingRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSupportRoute: typeof AppSupportRoute
  AppAdminApplicationsRoute: typeof AppAdminApplicationsRoute
  AppAdminCategoriesRoute: typeof AppAdminCategoriesRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminPaymentsRoute: typeof AppAdminPaymentsRoute
  AppAdminRequestsRoute: typeof AppAdminRequestsRoute
  AppAdminSupportRoute: typeof AppAdminSupportRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppClientDashboardRoute: typeof AppClientDashboardRoute
  AppProBillingRoute: typeof AppProBillingRoute
  AppProDashboardRoute: typeof AppProDashboardRoute
  AppProMatchingRoute: typeof AppProMatchingRouteWithChildren
  AppProOnboardingRoute: typeof AppProOnboardingRoute
  AppProResponsesRoute: typeof AppProResponsesRoute
  AppProSubscriptionRoute: typeof AppProSubscriptionRoute
  AppClientRequestsIdRoute: typeof AppClientRequestsIdRoute
  AppClientRequestsNewRoute: typeof AppClientRequestsNewRoute
  AppClientRequestsIndexRoute: typeof AppClientRequestsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSupportRoute: AppSupportRoute,
  AppAdminApplicationsRoute: AppAdminApplicationsRoute,
  AppAdminCategoriesRoute: AppAdminCategoriesRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminPaymentsRoute: AppAdminPaymentsRoute,
  AppAdminRequestsRoute: AppAdminRequestsRoute,
  AppAdminSupportRoute: AppAdminSupportRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppClientDashboardRoute: AppClientDashboardRoute,
  AppProBillingRoute: AppProBillingRoute,
  AppProDashboardRoute: AppProDashboardRoute,
  AppProMatchingRoute: AppProMatchingRouteWithChildren,
  AppProOnboardingRoute: AppProOnboardingRoute,
  AppProResponsesRoute: AppProResponsesRoute,
  AppProSubscriptionRoute: AppProSubscriptionRoute,
  AppClientRequestsIdRoute: AppClientRequestsIdRoute,
  AppClientRequestsNewRoute: AppClientRequestsNewRoute,
  AppClientRequestsIndexRoute: AppClientRequestsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SearchRoute: SearchRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ProsProIdRoute: ProsProIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
